### ISSUE TITLE
Cross-check with Azure Container Registry

### ISSUE THREAD

**Issue by StefanScherer** [caleblloyd/gcr-windows-container-bug#1]
Hello @caleblloyd!

Nice catch :-)

I've just tried the Azure Container Registry for comparison (see this [blog post](https://ahmetalpbalkan.com/blog/azure-container-registry/) for details), but this already supports Windows Container images.

```
PS C:\> docker tag stefanscherer/vx:576 registryss-on.azurecr.io/vx:576
PS C:\> docker push registryss-on.azurecr.io/vx:576
The push refers to a repository [registryss-on.azurecr.io/vx]
e5287a24a5e3: Pushed
de57d9086f9a: Skipped foreign layer
f358be10862c: Skipped foreign layer
576: digest: sha256:4ab9f1cb12144baa600e9bf7eed4e1df0fa9183e0c5ee090703d386b81ba4f21 size: 1152
```

The two foreign base layers will be skipped as they reside at Microsoft's CDN. But the registry is able to work with these foreign layers.

```
PS C:\> docker pull registryss-on.azurecr.io/vx:576
576: Pulling from vx
3889bb8d808b: Already exists
04ee5d718c7a: Already exists
23530c9dbd1c: Pull complete
Digest: sha256:4ab9f1cb12144baa600e9bf7eed4e1df0fa9183e0c5ee090703d386b81ba4f21
Status: Downloaded newer image for registryss-on.azurecr.io/vx:576
```

**Comment by caleblloyd** [comment]
I exchanged a few emails with the Google Container Registry team on Friday and they have a fix that should be landing soon.  Windows containers images have some extra fields that get sent up in the manifest.

**Comment by StefanScherer** [comment]
That's great. I'll close this one.
